version: 2.1

jobs:
  security-check:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Setup
          command: sudo make install-vulnerabilities-checker
      - run:
          name: Check
          command: make check-vulnerabilities
  lint-n-test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            make install-mflow-runner
            make install-mflow-runner-tests
      - run:
          name: Lint
          command: |
            make lint-mflow-runner
      - run:
          name: Test
          command: |
            make test-mflow-runner
            odahu-flow-mlflow-runner -h
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Build
          command: |
            make docker-build-mlflow-trainer-integration
            make docker-build-mlflow-tracking-server

workflows:
  main:
    jobs:
      - security-check
      - lint-n-test:
          requires:
            - security-check
      - build:
          context:
            - hub.docker.com
          requires:
            - lint-n-test
