{{- if .Values.tracking_server.enabled -}}
{{- if (ternary $.Values.tracking_server.ingress.enabled $.Values.ingress.enabled (hasKey $.Values.tracking_server.ingress "enabled")) }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- include "odahuflow.ingress-aggregated-annotations" (dict "local" .Values.tracking_server.ingress "root" .) | nindent 4 }}
  labels:
    component: "odahuflow-mlflow-tracking-server"
    {{- include "odahuflow.helm-labels" . | nindent 4 }}
  name: "{{ .Release.Name }}-mlflow-tracking-server"
spec:
  rules:
    - host: {{ include "odahuflow.ingress-domain-name" (dict "local" .Values.tracking_server.ingress "root" . "tpl" "%s") }}
      http:
        paths:
          - backend:
              serviceName: "mlflow"
              servicePort: {{ .Values.tracking_server.port }}
            path: "{{ .Values.tracking_server.ingress.path }}(/api.*)"
          - backend:
              serviceName: "mlflow"
              servicePort: {{ .Values.tracking_server.port }}
            path: "/kek"
            path: '/({{ .Values.tracking_server.ingress.path | trimPrefix "/" }}.*)'
  {{- if (ternary $.Values.tracking_server.ingress.tlsEnabled $.Values.ingress.tlsEnabled (hasKey $.Values.tracking_server.ingress "tlsEnabled")) }}
  tls:
  - hosts:
    - {{ include "odahuflow.ingress-domain-name" (dict "local" .Values.tracking_server.ingress "root" . "tpl" "%s") | quote }}
    secretName: {{ include "odahuflow.ingress-tls-secret-name" (dict "local" .Values.tracking_server.ingress "root" . ) | quote }}
  {{- end }}
{{- end }}
{{- end }}
